title: "Ben Severns"
description: "Portfolio â€” studio + teaching"
collections:
  projects:
    output: true
    permalink: /projects/:name/
  teaching:
    output: true
    permalink: /teaching/:name/
  nodes:
    output: true
    permalink: /atlas/n/:name/
defaults:
  - scope: {path: "", type: "projects"}
    values:
      layout: project
      author: "Ben Severns"
      archived: true
  - scope: {path: "", type: "teaching"}
    values:
      layout: teaching
      author: "Ben Severns"
      archived: true
  - scope: {path: "", type: "nodes"}
    values:
      layout: atlas_node
      author: "Ben Severns"
markdown: kramdown
